### ISSUE TITLE
[Android]显示出来了 有点问题。

### ISSUE THREAD

**Issue by zetaoWu** [laoqiu/react-native-amap#5]
![image](https://cloud.githubusercontent.com/assets/23578703/21253628/12c09564-c39b-11e6-9d50-3ed472c656b7.png)

1. 跟着作者 重写了桥接原生UI
 ` <AMapView  mode={1} style={{flex:1,width:widthSrc,height:heightSrc}} />`
如果我使用了定位参数
<AMapView  mode={1} **showsUserLocation={true}** style={{flex:1,width:widthSrc,height:heightSrc}} /> 报错 找不到该showsUserLocation参数 。是我使用错误吗？  

 @laoqiu 作者有空的话。可以解答一下。  谢谢哈

**Comment by laoqiu** [comment]
我还是把项目中比较新的版本更新到github上，你再看下。稍等一下
